# Generated by Django 4.1.5 on 2023-02-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.CharField(max_length=60),
        ),
    ]
